### ISSUE TITLE
How do we modify an existing textgrid?

### ISSUE THREAD

**Issue by mamadyonline** [hbuschme/TextGridTools#23]
Hello,

Here is my issue. I have a text grid file where the end time is "wrong", and I want to edit it. Is there a way to do this with TGT? 
I have directly tried to set the end_time attribute of the TGT object, but it does not work. I can't find a workaround that would work for me directly without creating a text grid from scratch.

Thanks for your help

**Comment by hbuschme** [comment]
The `start_time` and `end_time` attributes of a TextGrid object are read only since they dynamically return the smallest start time and the largest end time of the object's tiers. To manually change the start/end time of a TextGrid object to a certain value, you can set the start/end time of at least one of its tiers to that value, e.g., as follows:

```
>>> tg = tgt.read_textgrid("text.TextGrid")
>>> print(tg.end_time)
318.37
>>> tg.tiers[0].end_time = 500
500.0
>>> print(tg.end_time)
```
